id: I55BDD040
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:03:03+00:00'
last_modified: '2022-06-08T08:24:22.010522+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W11575
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8977':
      image_group_id: I1KG2221
      title: ''
      total_pages: 98
      order: 1
      base_file: 8977.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
