id: P008274
initial_creation_type: ocr
source_metadata:
  id: bdr:W11575
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་འབྱུང
  author: ''
  volumes:
    f0e28e27fb6a47ba8f937227cedb3333:
      image_group_id: I1KG2221
      title: ''
      volume_number: 1
      total_pages: 98
