id: P008274
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W11575
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་འབྱུང
  author: ''
  volumes:
    f0e28e27fb6a47ba8f937227cedb3333:
      image_group_id: I1KG2221
      title: ''
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
